### ISSUE TITLE
"The panorama can't be loaded" when embedded inside app browser

### ISSUE THREAD

**Issue by user080975** [sk-zk/lookaround-map#12]
Hi,

Everything is working fine in iOS Safari but when I embed the page inside Capacitor, I get the following error:
"The panorama can't be loaded"

Do you have any idea what would the reason or error that's causing this issue? Is it something to do with Three JS or the canvas element? I have a Three JS app inside Capacitor and didn't have any problems.

**Comment by sk-zk** [comment]
I'm not familiar with Capacitor, sorry. Any console errors?

**Comment by user080975** [comment]
This is the console error I see

![2024-05-14 at 18 50 00](https://github.com/sk-zk/lookaround-map/assets/54892636/35b59873-f9cb-43b3-a3fc-7d1a24e04e4a)
![2024-05-14 at 18 50 14](https://github.com/sk-zk/lookaround-map/assets/54892636/63b56277-9579-4c65-bbe2-2055a3b61955)

**Comment by sk-zk** [comment]
Do you have a stack trace? That function never gets called on my end

**Comment by user080975** [comment]
This is what I see when I expand the error. Do you have any idea why the t.image is undefined?

![2024-05-14 at 21 01 39](https://github.com/sk-zk/lookaround-map/assets/54892636/70cbd549-cb7f-424c-8d69-139318a80827)

**Comment by sk-zk** [comment]
You can see here that `showError` is called first. As best I can tell, this is only called if `setPanorama` fails to load the panorama faces, so you should take a look at those network calls next.

**Comment by user080975** [comment]
Thanks that solved the problem!
