### ISSUE TITLE
Microsoft Defender warns of potentially malicious content

### ISSUE THREAD

**Issue by Flowsen123** [sk-zk/lookaround-map#15]
MS Teams blocks the link and on opening, Edge warns to open the page for potentially malicious content

![image](https://github.com/sk-zk/lookaround-map/assets/172502543/145429cd-26bf-4b07-89a5-2745985112c7)

**Comment by sk-zk** [comment]
Definitely a false positive. Is there any explanation as to what triggered this ranking?
