### ISSUE TITLE
Lookaround not working on Firefox anymore

### ISSUE THREAD

**Issue by sha-265** [sk-zk/lookaround-map#17]
I'm trying to use your website with Firefox 131.0, but unable to view any street view. It used to work before on Firefox.

When clicking on streets, nothing happens.

**Comment by sk-zk** [comment]
Are there any errors in the console?

**Comment by sk-zk** [comment]
Looks like WebGL is disabled in your browser. Try this: https://help.interplaylearning.com/en/help/how-to-enable-webgl-in-firefox

**Comment by sha-265** [comment]
Ok, I restarted the browser and it's working. Probably GPU driver update cause this. Thanks
