### ISSUE TITLE
Look around doesn't load in iOS Safari

### ISSUE THREAD

**Issue by user080975** [sk-zk/lookaround-map#8]
Hi,

I tested the demo here:
https://lookmap.eu.pythonanywhere.com

But it doesn't seem to load on Safari on iOS 17.3.1, which is the latest. Is it possible to get this working on iOS Safari? I don't see any errors in console either. 

Thanks!

**Comment by sk-zk** [comment]
I may have tracked down the issue. Does this page show "the script didn't run" for you? 

https://sk-zk.github.io/hevc-msp/

**Comment by user080975** [comment]
Yea I got the “script didn’t run” message on that page.

**Comment by sk-zk** [comment]
The site should be fixed now.

**Comment by user080975** [comment]
Just tried it and it works great! Is the example based on Three JS? Would it be possible to modify the transition to a cross fade or some other transition similar to the one Apple or Google uses?

**Comment by sk-zk** [comment]
>Is the example based on Three JS?

Yep, panoramas are rendered with [Photo Sphere Viewer](https://photo-sphere-viewer.js.org/) which uses Three.js. 

>Would it be possible to modify the transition to a cross fade or some other transition similar to the one Apple or Google uses?

The transitions in Look Around are made by morphing between the 3D meshes associated with each panorama. I've yet to work out how to decompress them, but if I ever do, I'll try to integrate them into the viewer.
